plugins {
    id 'com.android.application'
}

android {
    namespace 'fr.deleguefootball.android8'
    compileSdk 35

    defaultConfig {
        applicationId 'fr.deleguefootball.android8'
        minSdk 26
        targetSdk 28
        versionCode 59
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
